package seed

import "math/rand"

// prng is the single source of pseudo-randomness in this package.
//
// It wraps one *math/rand.Rand constructed explicitly from the scenario seed by
// [newPRNG]; there is no global source, no time-based source and no second
// generator anywhere in the package. math/rand's sequence for a fixed seed is
// covered by the Go 1 compatibility promise, so the same seed yields the same
// draws on every supported toolchain, which is what makes the generated bytes
// reproducible.
//
// The only rule callers must honor is that draws happen in a fixed order:
// [Generate] documents the phase order and every phase iterates slices, never
// maps.
type prng struct{ r *rand.Rand }

// newPRNG returns the generator for a scenario seed.
func newPRNG(seed int64) *prng { return &prng{r: rand.New(rand.NewSource(seed))} }

// intn returns a pseudo-random int in [0, n). n must be positive.
func (p *prng) intn(n int) int {
	if n <= 1 {
		return 0
	}
	return p.r.Intn(n)
}

// between returns a pseudo-random int in [lo, hi]. lo must not exceed hi.
func (p *prng) between(lo, hi int) int {
	if hi <= lo {
		return lo
	}
	return lo + p.r.Intn(hi-lo+1)
}

// chance reports whether an event with probability numerator/1000 occurs. It is
// expressed in per-mille so no float64 enters the generator.
func (p *prng) chance(perMille int) bool { return p.r.Intn(1000) < perMille }

// pickString returns one element of a non-empty slice.
func (p *prng) pickString(xs []string) string { return xs[p.intn(len(xs))] }

// perm returns a pseudo-random permutation of [0, n).
func (p *prng) perm(n int) []int { return p.r.Perm(n) }
